# FT-75, FT-76: Generated by Django 5.2.18 on 2026-10-08 16:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=7)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.CharField(max_length=255)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Every two weeks'), ('monthly', 'Monthly')], max_length=8)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('next_due_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_due_date', 'description'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='recurring_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_transactions', to='transactions.recurringtransaction'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('recurring_source__isnull', False)), fields=('recurring_source', 'date'), name='unique_recurring_occurrence'),
        ),
        migrations.AddIndex(
            model_name='recurringtransaction',
            index=models.Index(fields=['user', 'is_active', 'next_due_date'], name='transaction_user_id_4b770c_idx'),
        ),
        migrations.AddConstraint(
            model_name='recurringtransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='recurring_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='recurringtransaction',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='recurring_end_after_start'),
        ),
    ]
